### ISSUE TITLE
Issues #2

### ISSUE THREAD

**Issue by PiotrChylak** [chudkowsky/car-rental-io#3]
1. We have to finish getVehiclesFromCSV method, also we have to consider if we want to saveUsers all at once or meaby one by one when we creating them.
2. rent and return methods are more complicated than we thought and we have to come up with new solution.
3. we can still refractor our code more

**Comment by chudkowsky** [comment]
2. i implementad those 2 methods, now we have to see if it is working as expected

**Comment by chudkowsky** [comment]
we should add ratings for each borrower and lender also to do automated acceptation of rent request

**Comment by chudkowsky** [comment]
Perfect work, its really nice to work with you buddy (if you are from HR then i wanted you to see that)
